# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest before commit on tests/ folder
        entry: pytest --maxfail=1 --disable-warnings -q
        language: system
        types: [python]
        args: ["tests/"]

