name: Run Tests

on:
  pull_request:   # 👈 triggers when PR is raised
  push:           # optional: also run on push
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY }}
      GROQ_API_KEY: ${{secrets.GROQ_API_KEY }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest tests/ --maxfail=1 --disable-warnings -q

